### ISSUE TITLE
Split configs

### ISSUE THREAD

**Issue by LogansUA** [itrascastro/Symfony-3-Base-Project#1]
Hello.

Maybe better will be with already split configs something like that:
`doctrine/doctrine.yml`:

``` YML
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
```

`doctrine/extionsions.yml`

``` YML
services:
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
```

`fos/user.yml`:

``` YML
# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Trascastro\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: true
    from_email:
        address:        youremailaccount@gmail.com
        sender_name:    YourSenderName
```

`knp/paginator.yml`:

``` YML
# KnpPaginatorBundle Configuration
knp_paginator:
    page_range: 2                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
```

And include them all in `config.yml`:

``` YML
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine/doctrine.yml }
    - { resource: doctrine/extensions.yml }
    - { resource: fos/user.yml }
    - { resource: knp/paginator.yml }

...
```

I always do something like that before starting new project.
